[options]
addons_path = c:\Users\D\Downloads\odoo-19.0\odoo-19.0\odoo\addons,c:\Users\D\Downloads\odoo-19.0\odoo-19.0\addons
db_host = localhost
db_port = 5432
db_user = odoo
db_password = Althakeb@2030
admin_passwd = $pbkdf2-sha512$600000$G2OM8X6vtRZCCCHk3HuPEQ$zLRrC9WQncRcLXHEe20KXFcRj6/C0jJHTqU8mQrXv8j65e4Jc40cyHXESRQU1wFztskFrxOrglgVmS/tdY40HA
http_port = 8069
http_interface = 127.0.0.1
db_name = odoo19

