[options]
addons_path = ./odoo/addons,./addons
db_host = localhost
db_port = 5432
db_user = odoo
db_password = CHANGE_ME
admin_passwd = $pbkdf2-sha512$600000$G2OM8X6vtRZCCCHk3HuPEQ$zLRrC9WQncRcLXHEe20KXFcRj6/C0jJHTqU8mQrXv8j65e4Jc40cyHXESRQU1wFztskFrxOrglgVmS/tdY40HA
http_port = 8069
http_interface = 127.0.0.1
db_name = odoo19

